ulimit -c unlimited

export PATH=$HOME/bin:$PATH

# Useful aliases
alias ls='ls $LS_OPTIONS'
alias lk='ls $LS_OPTIONS -1'
alias ll='ls $LS_OPTIONS -lh'
alias la='ls $LS_OPTIONS -lA'
alias cd..="cd .."
alias ..="cd .."
alias lc='wc -l'
alias duh='du -csh'
alias t='date -ur'
alias utc='date -u'

alias db='debuild -b -us -uc'

PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    ;;
*)
    ;;
esac
